apiVersion: v2
name: ctwall
description: Unified Helm chart for CTWall (backend + frontend + optional PostgreSQL)
type: application
version: 1.2.1
appVersion: "1.2.1"

dependencies:
  - name: postgresql
    version: 18.6.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: ctwall-backend
    alias: backend
    version: 1.2.1
    repository: file://../../backend/helm/ctwall-backend
    condition: backend.enabled
  - name: ctwall-frontend
    alias: frontend
    version: 1.2.1
    repository: file://../../frontend/helm/ctwall-frontend
    condition: frontend.enabled
