apiVersion: v1
kind: Service
metadata:
  name: {{ include "ctwall-frontend.fullname" . }}
  labels:
    {{- include "ctwall-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.service.httpEnabled }}
    - port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpTargetPort }}
      protocol: TCP
      name: http
    {{- end }}
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: https
  selector:
    {{- include "ctwall-frontend.selectorLabels" . | nindent 4 }}
